name: "elementary"
version: "0.18.0"

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2
profile: "elementary"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  +enabled: "{{ target.type != 'fabric' }}"

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"

on-run-start:
  - "{{ elementary.on_run_start() if target.type != 'fabric' }}"
on-run-end:
  - "{{ elementary.on_run_end() if target.type != 'fabric' }}"
