version: "3.8"

services:
  spark-connect:
    container_name: spark-connect
    build:
      context: ./docker/spark
      dockerfile: Dockerfile
    ports:
      - "15002:15002"
      - "4040:4040"
    depends_on:
      - spark-hive-metastore
    command: >
      --class org.apache.spark.sql.connect.service.SparkConnectServer
      --name Spark Connect Server
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 15002"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    volumes:
      - spark-warehouse:/spark-warehouse/
      - ./docker/spark/hive-site.xml:/usr/spark/conf/hive-site.xml
      - ./docker/spark/spark-defaults.conf:/usr/spark/conf/spark-defaults.conf
    environment:
      - WAIT_FOR=spark-hive-metastore:5432
      - SPARK_CONNECT_GRPC_BINDING_PORT=15002

  spark-hive-metastore:
    image: postgres:15-alpine
    volumes:
      - hive-metastore:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbt
      - POSTGRES_PASSWORD=dbt
      - POSTGRES_DB=metastore

volumes:
  spark-warehouse:
  hive-metastore:
