services:
  # Nessie Catalog Server Using In-Memory Store
  nessie:
    image: projectnessie/nessie:latest
    container_name: catalog
    networks:
      - dremio-lakehouse
    ports:
      - 19120:19120

  # Minio Storage Server
  minio:
    image: minio/minio:latest
    container_name: storage
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      - dremio-lakehouse
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data

  minio-setup:
    image: minio/mc
    container_name: minio-setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (echo > /dev/tcp/minio/9000) >/dev/null 2>&1; do
        echo 'Waiting for MinIO...';
        sleep 2;
      done;
      mc alias set myminio http://minio:9000 admin password;
      mc mb myminio/datalake;
      mc ls myminio;
      "
    networks:
      - dremio-lakehouse

  # Dremio
  dremio:
    image: dremio/dremio-oss:latest
    platform: linux/amd64
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
      - 45678:45678
    container_name: dremio
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist -Ddebug.addDefaultUser=true
      - SERVICES_COORDINATOR_ENABLED=true
      - SERVICES_EXECUTOR_ENABLED=true
    networks:
      - dremio-lakehouse
    volumes:
      - dremio_data:/opt/dremio/data:rw
    # Workaround for permission issues in podman
    user: "0"

  dremio-setup:
    image: alpine:latest
    container_name: dremio-setup
    depends_on:
      - dremio
    volumes:
      - ./docker/dremio/dremio-setup.sh:/dremio-setup.sh
    command: sh /dremio-setup.sh
    networks:
      - dremio-lakehouse

networks:
  dremio-lakehouse:

volumes:
  dremio_data:
  minio_data:
