version: "3.8"

services:
  spark-thrift:
    build:
      context: ./docker/spark
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
      - "4040:4040"
    depends_on:
      - spark-hive-metastore
    command: >
      --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
      --name Thrift JDBC/ODBC Server
    volumes:
      - spark-warehouse:/spark-warehouse/
      - ./docker/spark/hive-site.xml:/usr/spark/conf/hive-site.xml
      - ./docker/spark/spark-defaults.conf:/usr/spark/conf/spark-defaults.conf
    environment:
      - WAIT_FOR=spark-hive-metastore:5432

  spark-hive-metastore:
    image: postgres:9-alpine
    volumes:
      - hive-metastore:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbt
      - POSTGRES_PASSWORD=dbt
      - POSTGRES_DB=metastore

volumes:
  spark-warehouse:
  hive-metastore:
