version: 2

models:
  - name: any_type_column_anomalies
    description: >
      This is a very weird description
      with breaklines
      and comma,
      and even a string like this 'wow'. You know, these $##$34#@#!^ can also be helpful
      WDYT?
    config:
      elementary:
        timestamp_column: "updated_at"
    tests:
      - elementary.table_anomalies:
          config:
            severity: warn
          tags: ["table_anomalies"]
          table_anomalies:
            - row_count
      - elementary.all_columns_anomalies:
          tags: ["all_any_type_columns_anomalies"]
          #This here is to simulate a long test name as test params are part of the test name
          exclude_regexp: ".*column1|column2|column3|column4|column5|column6|column7|column8|column9|column10|column11|column12|column13|column14|column15|column16|column17.*"
      - generic_test_on_model:
          tags: ["regular_tests"]

  - name: no_timestamp_anomalies
    description: We use this model to test anomalies when there is no timestamp column
    tests:
      - elementary.table_anomalies:
          tags: ["no_timestamp"]
          table_anomalies:
            - row_count
    columns:
      - name: "null_count_str"
        tests:
          - elementary.column_anomalies:
              tags: ["no_timestamp"]
              column_anomalies:
                - null_count

  - name: error_model
    description: We use this model to create error runs and tests
    columns:
      - name: "missing_column"
        tests:
          - uniques:
              tags: ["error_test"]

  - name: string_column_anomalies
    meta:
      owner: "@or"
      tags: ["marketing"]
    config:
      elementary:
        timestamp_column: "updated_at"
    tests:
      - elementary.table_anomalies:
          tags: ["table_anomalies"]
          table_anomalies:
            - freshness
      - elementary.all_columns_anomalies:
          tags: ["all_string_column_anomalies"]
      - elementary.schema_changes:
          tags: ["schema_changes"]
    columns:
      - name: "min_length"
        tests:
          - relationships:
              tags: ["regular_tests"]
              to: source('training', 'string_column_anomalies_training')
              field: max_length
          - elementary.column_anomalies:
              tags: ["string_column_anomalies"]
              column_anomalies:
                - min_length
                - max_length
                - missing_count
      - name: max_length
        tests:
          - elementary.column_anomalies:
              tags: ["string_column_anomalies"]
      - name: average_length
        tests:
          - elementary.column_anomalies:
              tags: ["string_column_anomalies"]
              column_anomalies:
                - average_length
                - null_count
      - name: missing_count
        tests:
          - elementary.column_anomalies:
              tags: ["string_column_anomalies"]
      - name: missing_percent
        tests:
          - elementary.column_anomalies:
              tags: ["string_column_anomalies"]
      - name: updated_at
        tests:
          - elementary.column_anomalies:
              tags: ["string_column_anomalies"]

  - name: numeric_column_anomalies
    config:
      elementary:
        timestamp_column: "updated_at"
    tests:
      - elementary.table_anomalies:
          tags: ["table_anomalies"]
      - elementary.schema_changes:
          tags: ["schema_changes"]
      - elementary.all_columns_anomalies:
          tags: ["all_numeric_columns_anomalies"]
          column_anomalies:
            - average_length
            - null_count
    columns:
      - name: min
        tests:
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
              column_anomalies:
                - min
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
              column_anomalies:
                - max
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
              column_anomalies:
                - average
      - name: max
        tests:
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
              column_anomalies:
                - min
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
              column_anomalies:
                - max
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
              column_anomalies:
                - average
      - name: average
        tests:
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
              column_anomalies:
                - min
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
              column_anomalies:
                - max
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
              column_anomalies:
                - average
      - name: zero_count
        tests:
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
      - name: zero_percent
        tests:
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
      - name: updated_at
        tests:
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
      - name: variance
        tests:
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]
      - name: standard_deviation
        tests:
          - elementary.column_anomalies:
              tags: ["numeric_column_anomalies"]

sources:
  - name: training
    schema: "{{ target.schema }}"
    tables:
      - name: any_type_column_anomalies_training
        tests:
          - elementary.table_anomalies:
              tags: ["table_anomalies"]
      - name: string_column_anomalies_training
        meta:
          elementary:
            timestamp_column: "date"
        tests:
          - elementary.table_anomalies:
              tags: ["table_anomalies"]
      - name: numeric_column_anomalies_training
  - name: validation
    schema: "{{ target.schema }}"
    tables:
      - name: any_type_column_anomalies_validation
        tests:
          - elementary.all_columns_anomalies:
              tags: ["elementary_source"]
        columns:
          - name: null_count_int
            tests:
              - generic_test_on_column:
                  tags: ["regular_tests"]
  - name: schema_changes_data
    schema: "{{ target.schema }}"
    tables:
      - name: groups
        tests:
          - elementary.schema_changes:
              tags: ["schema_changes"]
      - name: stats_players
        tests:
          - elementary.schema_changes:
              tags: ["schema_changes"]
      - name: stats_team
        tests:
          - elementary.schema_changes:
              tags: ["schema_changes"]
