name: Remind docs
on:
  pull_request:
    branches: [ "master" ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            Thank you for raising your pull request.
            Please make sure you have documented all user-facing changes in the docs.
            You can do this by editing the `docs` files in the [`elementary`](https://github.com/elementary-data/elementary) repository.