spark.driver.memory                    2g
spark.executor.memory                  2g
spark.hadoop.datanucleus.autoCreateTables       true
spark.hadoop.datanucleus.schema.autoCreateTables true
spark.hadoop.datanucleus.fixedDatastore          false
spark.serializer                       org.apache.spark.serializer.KryoSerializer
spark.driver.userClassPathFirst        true
